import './PoliticaDeCookies.css'

function PoliticaDeCookies() {

    return(
      <div>
        <h1 id='header1'>Política de Cookies</h1>
        <div className='bodyCookies'>
          <div className='mainCookies'>En cumplimiento de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio Electrónico (en adelante, “LSSI”), que se refiere a la utilización de cookies, Adrenathure informa a los usuarios que la web utiliza cookies para poder medir y analizar el tráfico, con el fin de facilitar la experiencia y ofrecer un mejor servicio. El usuario puede configurar su navegador para ser avisado en pantalla de la recepción de cookies, o bien para impedir su instalación, en cuyo caso, cabe la posibilidad de que deje de tener acceso a ciertas funciones en Internet.</div>
          <h3 id='header3'>1.- DEFINICIÓN Y FUNCIÓN DE LAS COOKIES</h3>
          <div className='mainCookies'>Una cookie es un pequeño archivo creado por un sitio en Internet con la función de almacenar información en el equipo del usuario. Cuando se accede a un sitio web que utiliza cookies, se solicita al navegador que guarde una o más cookies en el disco duro. </div>
          <div className='mainCookies'>Cuando el usuario vuelve a ese sitio web, el navegador envía de nuevo las cookies que le pertenecen, para así prestar un servicio e información personalizada en función de las necesidades del mismo.</div>
          <div className='mainCookies'>Las cookies también pueden llegar a guardar información que identifique personalmente a los usuarios, no siendo el caso de esta web, que sólo tendrá acceso a la información personal que el usuario decida proporcionar.</div>
          <div className='mainCookies'>Es posible cambiar la configuración de cookies del navegador que el usuario utiliza, para que le permita aprobar o rechazar automáticamente peticiones de almacenamiento de cookies cuando se cierra el navegador, además de otras opciones adicionales.</div>
          <h3 id='header3'>2.- TIPOS DE COOKIES QUE UTILIZA ESTA PÁGINA WEB</h3>
          <div className='mainCookies'>Esta web puede utilizar cookies propias técnicas para las cuales no es necesaria la obtención del consentimiento del usuario, por encontrarse excluidas del ámbito de aplicación del artículo 22. 2 de la LSSI.</div>
          <div className='mainCookies'>Además, utiliza cookies que requieren el consentimiento de los usuarios, las cuales serán enunciadas en este apartado:</div>
          <ul>
            <li className='mainCookies3'><span>Técnicas</span>: facilitan información sobre el uso que el usuario realiza de la web. No permiten identificar al usuario, porque la información que recogen es anónima y se utiliza únicamente para acciones de mejora que permitan que la web funcione de manera más ágil y adaptada a las preferencias de los usuarios.</li>
            <li className='mainCookies3'><span>De registro</span>: se crean tras el registro o cuando un usuario inicia sesión en la web.</li>
            <li className='mainCookies3'><span>De personalización</span>: permiten personalizar las funciones o contenidos de la web en función de los datos obtenidos del navegador.</li>
            <li className='mainCookies3'><span>Analíticas</span>: tienen fines estadísticos, de forma que la información se utiliza para medir la actividad, mediante Google Analytics, que es una herramienta gratuita de análisis web proporcionada por Google, permitiendo a los propietarios de los sitios web conocer cómo interactúan los usuarios con su sitio web.</li>
            <li className='mainCookies3'><span>Preferencias</span>: permiten saber si el usuario ha visitado antes la web. La pérdida de información almacenada en una cookie de preferencias puede hacer que la experiencia de la web sea menos funcional, pero no debe afectar a su funcionamiento.</li>
            <li className='mainCookies3'><span>Estado de la sesión</span>: guardan la información necesaria durante la sesión y los cambios relacionados con ella, y también determinan si el usuario está registrado.</li>
            <li className='mainCookies3'><span>Procesos</span>: permiten el funcionamiento de la web y ofrecen servicios esperados por el usuario que accede a la misma.</li>
          </ul>
          
          
          
          
          <h3 id='header3'>3.- Finalidad de la web</h3>
          <div className='mainCookies'>La web de adrenathure tiene la finalidad de informar a clientes y potenciales clientes de sus productos y/o servicios, datos de contacto, ubicación, etc. Además, en su caso, también tendrá la finalidad de divulgar información relacionada con el sector de actividad del Responsable.</div>
          <h3 id='header3'>4.- Marco Normativo</h3>
          <div className='mainCookies'>La actividad de esta web se encuentra sujeta al marco legal español y europeo, concretamente a las siguientes normas:
          Reglamento General de Protección de Datos (RGPD) (UE) 2016/679, de 27 de abril, que regula el tratamiento de datos personales en los países de la Unión Europea.
          Ley Orgánica 3/2018, de 5 de diciembre, sobre Protección de Datos Personales y Garantía de los Derechos Digitales (LOPD y GDD), norma de ámbito regional (aplicable a España), y que define y amplía muchos de los conceptos y derechos presentes en el RGPD.</div>
          <h3 id='header3'>5.- Condiciones de Uso y Responsabilidades</h3>
          <div className='mainCookies'>Toda persona que acceda a este sitio web asume el papel de Usuario, comprometiéndose a la observancia y cumplimiento riguroso de las condiciones aquí dispuestas, así como a cualquiera otra disposición legal que fuera de aplicación. Adrenathure no se hará responsable de los daños y perjuicios, propios o a terceros, producidos por el uso inadecuado de este sitio web por parte del Usuario.
          El contenido de esta web, por tanto, no puede ser considerado, en ningún caso, sustitutivo de asesoramiento legal.</div>
          <div className='mainCookies'>Adrenathure se reserva el derecho a modificar cualquier tipo de información que pudiera aparecer en la web, en cualquier momento y sin previo aviso, sin que exista obligación de preavisar o poner en conocimiento de los Usuarios dichas obligaciones, entendiéndose como suficiente la publicación en el presente sitio web.
          Este sitio web ha sido revisado y probado para que funcione correctamente de manera ininterrumpida. No obstante, Adrenathure no descarta la posibilidad de que existan ciertos errores de programación, falta de disponibilidad puntual (por ejemplo, caídas del servidor, o mantenimiento del mismo) o que acontezcan causas de fuerza mayor, catástrofes naturales, huelgas, o circunstancias semejantes que hagan imposible el acceso temporal a la página web. De igual forma, Adrenathure no puede garantizar el funcionamiento ininterrumpido o totalmente libre de errores de esta web, ni se responsabiliza de los virus que tengan su origen en una transmisión telemática infiltrados por terceros generados con la finalidad de obtener resultados negativos para un sistema informático.</div>
          <div className='mainCookies'>El Usuario se compromete a no utilizar esta web ni, si es el caso, los servicios o productos ofrecidos en la misma, para la realización de actividades contrarias a la ley, al orden público o a estas condiciones de uso. Por tanto, adrenathure no se hace responsable de la información y contenidos almacenados, a título enunciativo, pero no limitativo, en foros, chats, generadores de blogs, comentarios, redes sociales o cualquier otro medio que permita a terceros publicar contenidos. No obstante, y en cumplimiento de lo dispuesto en el art. 11 y 16 de la LSSI-CE, adrenathure se pone a disposición de todos los Usuarios, autoridades y fuerzas de seguridad, colaborando de forma activa en la retirada o en su caso bloqueo de todos aquellos contenidos que pudieran afectar o contravenir la legislación nacional, o internacional, derechos de terceros, o la moral y el orden público. En caso de que un Usuario considere que existe en la web algún contenido que pudiera ser susceptible de esta clasificación, se ruega lo notifique de forma inmediata a nuestro personal.
          adrenathure se reserva el derecho a denegar o retirar el acceso a la web sin necesidad de advertencia previa, a instancia propia o de un tercero, a aquellos Usuarios que incumplan nuestras Condiciones de Uso.</div>
          <h3 id='header3'>6.- Propiedad intelectual</h3>
          <div className='mainCookies'>El sitio web, incluyendo a título enunciativo, pero no limitativo su programación, edición, compilación y demás elementos necesarios para su funcionamiento, los diseños, logotipos, texto y/o gráficos son propiedad de Adrenathure o, en su caso, dispone de licencia o autorización expresa por parte de los autores.
          Todos los contenidos del sitio web se encuentran debidamente protegidos por la normativa de propiedad intelectual e industrial, así como inscritos en los registros públicos correspondientes, y no se permite la reproducción y/o publicación, total o parcial, del sitio web, ni su tratamiento informático, su distribución, difusión, modificación o transformación, sin el permiso previo y por escrito del mismo. adrenathure velará por el cumplimiento de las anteriores condiciones, así como por la debida utilización de los contenidos presentados en sus páginas web, ejercitando todas las acciones civiles y penales que le correspondan en el caso de infracción o incumplimiento de estos derechos por parte del Usuario.</div>
          <div className='mainCookies'>Los diseños, logotipos, texto y/o gráficos ajenos a Adrenathure y que pudieran aparecer en el sitio web, pertenecen a sus respectivos propietarios, siendo ellos mismos responsables de cualquier posible controversia que pudiera suscitarse respecto a los mismos. En todo caso, Adrenathure cuenta con la autorización expresa y previa por parte de los mismos. Adrenathure reconoce a favor de sus titulares los correspondientes derechos de propiedad industrial e intelectual, no implicando su sola mención o aparición en el sitio web la existencia de derechos o responsabilidad alguna del Responsable sobre los mismos, como tampoco respaldo, patrocinio o recomendación por parte del mismo.</div>
          <h3 id='header3'>7.- Enlaces de terceros</h3>
          <div className='mainCookies'>Adrenathure puede poner a disposición del Usuario enlaces u otros elementos que permitan el acceso hacia otros sitios web pertenecientes a terceros. No comercializamos los productos y/o servicios de dichas páginas enlazadas, ni asumimos ningún tipo de responsabilidad sobre las mismas, ni sobre la información contenida en ellas, ni su veracidad o licitud, ni de cualesquiera efectos que pudieran derivarse.</div>
          <div className='mainCookies'>En todo caso, Adrenathure manifiesta que procederá a la retirada inmediata de cualquier contenido que pudiera contravenir la legislación nacional o internacional, la moral o el orden público, procediendo a la retirada inmediata de la redirección a dicho sitio web, poniendo en conocimiento de las autoridades competentes el contenido en cuestión.</div>
          <h3 id='header3'>8.- Ley aplicable y Jurisdicción</h3>
          <div className='mainCookies'>El idioma de redacción e interpretación de este aviso legal es el español.</div>
          <div className='mainCookies'>La relación entre Adrenathure y Usuario se rige en todos y cada uno de sus extremos por la ley española, a la que se someten expresamente ambas partes ante cualquier controversia o cuestión relacionada con el presente sitio web o las actividades en él desarrolladas.
          Por su parte, en el caso de que el usuario tenga su domicilio fuera de España, Adrenathure y Usuario se someten, con renuncia expresa a cualquier otro fuero, a los Juzgados y Tribunales competentes de España.</div>
          <h3 id='header3'>9.- Seguridad y Limitación de Responsabilidad</h3>
          <div className='mainCookies'>Adrenathure adoptará las medidas necesarias para asegurar la integridad del servicio disponible, y de los datos e información recogidos, pero no será responsable de lo que ocurra más allá de su control.
          En caso de que el usuario sea redirigido a otras páginas webs o plataformas de terceros, Adrenathure no se hará responsable de lo que ocurra a través de la navegación en las mismas.</div>
          <div className='mainCookies'>Esta página web está disponible en español, de forma que el titular no se hace responsable en caso de que el usuario no comprenda dicho idioma, ni de los actos que puedan derivar de su falta de comprensión.
          En la medida en que lo permita la ley, adrenathure no responde del uso incorrecto o imprudente que realicen los usuarios de “adrenathure.com”.
          Adrenathure no será responsable de incumplimientos o deficiencias que tengan causa de fuerza mayor o que estén fuera de su control razonable.</div>
          <h3 id='header3'>10.- Modificaciones y Nulidad</h3>
          <div className='mainCookies'>Adrenathure se reserva el derecho a actualizar y modificar estos textos legales, por lo que recomienda leer los mismos cada vez que se acceda o use la web.En caso de que alguna cláusula de estos Términos y Condiciones, Política de Privacidad o de Cookies, sea declarada total o parcialmente nula o ineficaz, dicha nulidad o ineficacia sólo afectará a la misma, subsistiendo las demás condiciones y teniéndose la disposición afectada por no puesta.</div>
          <h3 id='header3'>11.- Legislación aplicable y Jurisdicción competente</h3>
          <div className='mainCookies'>Estos Términos y Condiciones, y las Políticas de Privacidad y de Cookies, se interpretarán y regirán de conformidad con la legislación española. En caso de controversia, serán competentes los Juzgados de Vigo, con la renuncia expresa a cualquier otro fuero que pudiera corresponder, salvo disposición expresa de la ley.</div>
          <h3 id='header3'>12.- Contacto</h3>
          <div className='mainCookies'>En caso de duda, sugerencia o aclaración, el usuario se puede poner en contacto con adrenathure a través de la siguiente dirección de correo electrónico:</div>
          <div className='mainCookies2'>adrenathure.info@gmail.com</div>
        </div>
      </div>
    )
}

export default PoliticaDeCookies